import os, time

from tqdm import tqdm
from google_screenshot import GoogleCrawler
from yahoo_screenshot import YahooCrawler
from bing_screenshot import BingCrawler
# from instagram_screenshot import InstagramCrawler
# from face_cropper_mtcnn import mtcnnCropper

# out_path = '/media/luqmanr/TOSHIBA1TB/Thailand'
out_path = './Indonesia'

daftar_nama = [
  "tengku firmansyah",
  "tenno ali",
  "theresia ebenna ezeria pardede",
  "teresa bleszynski",
  "terry putri",
  "tetty kadi",
  "tetty liz indriati",
  "tetty manurung",
  "teuku ryan",
  "teuku ryzki",
  "teuku zacky",
  "thalita latief",
  "thomas djorghi",
  "thomas nawilis",
  "tiar ramon",
  "tien kadaryono",
  "tien sudrajat",
  "tika bisono",
  "tika putri",
  "tika ramlan",
  "tim matindas",
  "timbul suhardi",
  "tino karno",
  "tino saroengallo",
  "tio duarte",
  "tio fanta pinem",
  "titi dibyo",
  "titi dj",
  "titi dwijayati",
  "titi qadarsih",
  "titiek sandhora",
  "titien sumarni",
  "titik hamzah",
  "titim fatimah",
  "tito soemarsono",
  "tizza radia",
  "toar tangkau",
  "tommy j. pisa",
  "tommy kaganangan",
  "tony q rastafara",
  "tony taulo",
  "torro margens",
  "toto asmuni",
  "totos rasiti",
  "tri budiman",
  "tri yudiman",
  "trie utami",
  "trisa triandesa",
  "turino djunaedy",
  "tuti indra malaon",
  "tuti kembang mentari",
  "tuti maryati",
  "tuti mutia",
  "tutie kirana",
  "tuty s",
  "tuty subardjo",
  "tuty wasiat",
  "tya restyana",
  "tyara renata",
  "tyas dratistiana",
  "nyak ina raseuki ubiet",
  "ucie nurul",
  "ucok harahap",
  "ucup nirin",
  "ulfa dwiyanti",
  "uli herdinansyah",
  "ully artha",
  "ully sigar roesady",
  "ully triani",
  "umar lubis",
  "umar machdam",
  "umar syarief",
  "unique priscilla",
  "upit sarimanah",
  "urip arphan",
  "ussy sulistiawaty",
  "utha likumahuwa",
  "uty shaimoery",
  "uut permatasari",
  "vadi akbar",
  "valia rahma",
  "vani lauw",
  "varissa camelia",
  "vera detty",
  "verlita evelyn",
  "vety vera",
  "vicky burky",
  "vicky monica",
  "vicky shu",
  "vicky zainal",
  "victor hutabarat",
  "vienna fridiana",
  "viki vendy",
  "viky sianipar",
  "vina ferina",
  "vinessa inez",
  "violenzia jeanette",
  "viona rosalina",
  "vira talisa",
  "vira yuniar",
  "vista putri",
  "vitta mariana",
  "vivi samodro",
  "vivi sumanti",
  "volland humonggio",
  "vonny cornellya",
  "vonny kristianda",
  "vonny sumlang",
  "w.d. mochtar",
  "w.s. rendra",
  "wafiq azizah",
  "wahab abdi",
  "wahyu os",
  "wahyu sardono",
  "wahyu sihombing",
  "wanda nizar",
  "wangi gitaswara",
  "waty siregar",
  "wawa marisa",
  "wawan wanisar",
  "wendy wilson",
  "wichita satari",
  "widi dwinanda",
  "wieke widowati",
  "willy winarko",
  "winda amanta",
  "winda khair",
  "windy wulandari",
  "winnie yanthi",
  "wiwid gunawan",
  "wiwiek abidin",
  "wiwiek sumbogo",
  "wisnu prastowo wizzow",
  "wizzy williana",
  "wolly sutinah",
  "yani oktaviana yacko",
  "yan bastian",
  "yan cherry budiono",
  "yana julio",
  "yana zein",
  "yasamin jasem",
  "yati octavia",
  "yati pesek",
  "yati surachman",
  "yatni ardi",
  "yayuk suseno",
  "yefani filliang",
  "yemima hutapea",
  "yenny farida",
  "yenny rachman",
  "yessa iona gaffar",
  "yessi kenyang",
  "yessy gusman",
  "yetty loren",
  "yeyen lidya",
  "yoan tanamal",
  "yoelitta palar",
  "yohanna nainggolan",
  "yopie latul",
  "yoseano waas",
  "yosie lucky",
  "yova gracia",
  "ytonk club 80's",
  "yuanita budiman",
  "yudittia mayang",
  "yukino almira",
  "yulia rachman",
  "yunita david",
  "yunita siregar",
  "yuniza icha",
  "yurike prastika",
  "zahwa aqilah",
  "zaneta georgina",
  "zara leola",
  "zarima mir",
  "muhammad nizar zarro",
  "zeke khaseli",
  "zhi alatas",
  "zidni adam",
  "zora vidyanata",
  "zoraya perucha",
  "zsazsa utari",
  "zwesty wirahbuana",
  "adhareza",
  "aldisyah",
  "asmirandah",
  "basuki",
  "bonita",
  "darussalam",
  "eksanti",
  "fortunella",
  "gombloh",
  "ikranagara",
  "irsyadillah",
  "irwansyah",
  "kinaryosih",
  "krisdayanti",
  "krisyanto",
  "leonardo",
  "luanada",
  "mastur",
  "mayangsari",
  "maylaffayza",
  "mentari",
  "moza paramita",
  "nurnaningsih",
  "radhini",
  "rebecca soejati reijman",
  "reynavenzka",
  "rida farida",
  "shalvynne chang",
  "shazlin patria",
  "shelomita sulistiany",
  "syatatha",
  "tessy wahyuni",
  "Ruth Permatasari",
  "muhammad tulus",
  "valentino",
  "waldjinah",
  "widyawati",
  "wina natalia",
  "yunika",
  "adelia zahra"
]

def files(path):
    for file in os.listdir(path):
        if os.path.isfile(os.path.join(path, file)):
            yield file

for nama in daftar_nama:
    GoogleCrawler(nama, out_path)
    # YahooCrawler(nama, out_path)
    # BingCrawler(nama, out_path)
    # InstagramCrawler(nama, out_path)

    # print("cropping for", nama)
    # nama_path = os.path.join(out_path,nama)
    # filenames = files(nama_path)
    # for filename in filenames:
    #     mtcnnCropper(nama_path, filename)

    time.sleep(50)
